version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: gameverse-inventory-postgres
    environment:
      POSTGRES_USER: gameverse
      POSTGRES_PASSWORD: gameverse
      POSTGRES_DB: gameverse_inventory
    volumes:
      - gameverse-inventory-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gameverse -d gameverse_inventory"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: gameverse-inventory-redis
    ports:
      - "6379:6379"
    volumes:
      - gameverse-inventory-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: gameverse-inventory-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  gameverse-inventory-postgres-data:
    driver: local
  gameverse-inventory-redis-data:
    driver: local 