name: "🐛 Bug Report"
description: "Report a reproducible bug"
labels: "bug"
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: >-
        Please provide a minimal reproducible example (CLI commands, code, logs).
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform
      description: OS + version (Windows, Linux, macOS)
  - type: input
    id: version
    attributes:
      label: GameVerse version
      description: Output of `gameverse --version`
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I have read and agree to the Code of Conduct
          required: true 