name: Nightly Performance Demo

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  perf-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Performance Demo
        run: cargo run -p perf_demo --release

      - name: Upload performance report
        uses: actions/upload-artifact@v3
        with:
          name: perf_report
          path: perf_reports/perf_report.json 